### ISSUE TITLE
Please upload the code and data for the release chapters

### ISSUE THREAD

**Issue by somasays** [mahmoudparsian/data-algorithms-with-spark#2]
Though chapters have been released, the related code and data is not available, please do release them as well

**Comment by mahmoudparsian** [comment]
Hello Somasundaram,

I am finalizing the code for chapters and  will check them in to the GIT very soon…

Thank you for your patience and understandings.

If there is a specific question, which I can answer, please let me know.

best regards,
Mahmoud Parsian

**Comment by mahmoudparsian** [comment]
So far, I have checked in two chapter and working on other chapters...

**Comment by mahmoudparsian** [comment]
I have checked in code for 5 chapters and will be adding code for other chapters...
