### ISSUE TITLE
Missing Files On Github

### ISSUE THREAD

**Issue by michaelmiscanuk** [mahmoudparsian/data-algorithms-with-spark#26]
Hi,

You miss files for PageRank chapter on github. Data Files, and also pagerank_2.py

Thanks

**Comment by mahmoudparsian** [comment]
Hello,

Thank you for your message!
Yes, I added pagerank_2.py as:

https://github.com/mahmoudparsian/data-algorithms-with-spark/blob/master/code/chap08/python/page_rank/pagerank_2.py

Can you please let me know what data files are missing?

best regards,
Mahmoud

**Comment by mahmoudparsian** [comment]
Hello,

Thank you for your message!
Yes, I added pagerank_2.py as:

https://github.com/mahmoudparsian/data-algorithms-with-spark/blob/master/code/chap08/python/page_rank/pagerank_2.py

Can you please let me know what data files are missing?

best regards,
Mahmoud


    On Tuesday, September 6, 2022 at 10:08:26 AM PDT, Michael Miscanuk ***@***.***> wrote:  
 
 


Hi,

You miss files for PageRank chapter on github. Data Files, and also pagerank_2.py

Thanks
