### ISSUE TITLE
Code for chapter 9 is missing on github

### ISSUE THREAD

**Issue by michaelmiscanuk** [mahmoudparsian/data-algorithms-with-spark#27]
Hi,

code for chapter 9 is missing entirely, but you point here from the book, saying that we can find code here - https://github.com/mahmoudparsian/data-algorithms-with-spark/tree/master/code/chap09

Can you add please?

Like your book though. Thank you :)

**Comment by mahmoudparsian** [comment]
Hello Michael,
Thank you for your message and kind words.
Yes, I am working/completing the code for chapter 9.
Hope I will be able to post code for chapter 9 before the end of September 2022.

best regards,
Mahmoud

**Comment by mahmoudparsian** [comment]
post code for chapter 9 before the end of September 2022 (in progress).
